name: Feature

on:
  push:
    branches:
      - "feature/**"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "develop"
      - "main"
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  feature:
    uses: manmal/danger-spike-ci/.github/workflows/ios-feature.yml@workflows/ios/feature/v1
    with:
      repository_type: "swift_lib"
    secrets: inherit
